apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: otus-homework
build:
  artifacts:
  - image: osmenogg/observer
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/ingress.yaml
